services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BusinessFinder\BlockBundle\Resolver\BlockAliasResolver: ~
    BusinessFinder\BlockBundle\Twig\BlockExtension: ~