version: '2'

services:
    web:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx/horario
            - .:/var/www/html
        ports:
            - "8080:80"
        networks:
            - local

    php:
        build: docker/php/
        volumes:
            - .:/var/www/html
            - composer_cache:/var/www/.composer/cache
        networks:
            - local

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        mem_limit: 512M
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - index:/usr/share/elasticsearch/data
        # ports:
        #     - "9200:9200"
        #     - "9300:9300"
        networks:
            - local

    # kibana:
    #     image:  docker.elastic.co/kibana/kibana:5.4.0
    #     volumes:
    #         - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #     ports:
    #         - "81:5601"
    #     depends_on:
    #         - elasticsearch
    #     networks:
    #         - local

    mysql:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
        #ports:
        #    - "3306:3306"
        env_file:
            - ./docker/mysql/.env
        networks:
            - local
volumes:
    index: ~
    database: ~
    composer_cache: ~

networks:
    local:
        driver: bridge
