<?php declare(strict_types=1);

namespace BusinessFinder\EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findUpcomingEvents(): \Doctrine\ORM\Query
    {
        $qb = $this->createQueryBuilder('e');

        $qb->andWhere($qb->expr()->gte('e.startAt', ':now'))
            ->setParameter('now', (new \DateTime())->format('Y-m-d'));

        return $qb->getQuery();
    }
}
