<?php

namespace BusinessFinder\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
}
