<?php

namespace AppBundle\Repository;

/**
 * BusinessCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
