fos_elastica:
    serializer: ~
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        default:
            index_name: "%elastic_index_name%"
            types:
                business:
                    serializer:
                        groups: [elastic]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Business
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\Elasticsearch\BusinessElasticRepository
                business_category:
                    serializer:
                        groups: [elastic]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\BusinessCategory
                        provider: ~
                        finder: ~
                event:
                    serializer:
                        groups: [elastic]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Event
                        provider: ~
                        finder: ~