fos_elastica:
    clients:
        default: 
            host: "%elastic_host%"
            port: "%elastic_port%"
            headers:
                Authorization: "Basic %elastic_token%"
    indexes:
        default:
            index_name: "%elastic_index_name%"
            types:
                listing:
                    dynamic: strict
                    properties:
                        title: { type: text }
                        address: { type: text }
                        city: { type: keyword }
                        description: { type: text }
                        featured: { type: boolean }
                        categories:
                            type: nested
                            properties:
                                name:
                                    type: keyword
                                    fields:
                                        keyword: { type: keyword }
                                module: { type: text }
                        createdAt:
                            type: date
                            format: "strict_date_optional_time||epoch_millis"
                    persistence:
                        driver: orm
                        model: BusinessFinder\ListingBundle\Entity\Listing
                        provider: ~
                        finder: ~
                        repository: BusinessFinder\ListingBundle\Repository\Elasticsearch\BusinessElasticRepository

                category:
                    dynamic: strict
                    properties:
                        name:
                            type: text
                            fields:
                                keyword: { type: keyword }
                    persistence:
                        driver: orm
                        model: BusinessFinder\AppBundle\Entity\Category
                        provider: ~
                        finder: ~
                event:
                    dynamic: strict
                    properties:
                        title: { type: text }
                        description: { type: text }
                        startAt:
                            type: date
                            format: "strict_date_optional_time||epoch_millis"
                        endAt:
                            type: date
                            format: "strict_date_optional_time||epoch_millis"
                        recurrent: { type: boolean }
                    persistence:
                        driver: orm
                        model: BusinessFinder\EventBundle\Entity\Event
                        provider: ~
                        finder: ~
                deal:
                    dynamic: strict
                    properties:
                        title: { type: text }
                        description: { type: text }
                        price: { type: double }
                    persistence:
                        driver: orm
                        model: BusinessFinder\DealBundle\Entity\Deal
                        provider: ~
                        finder: ~
