security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ROLE_ADMIN]}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            logout: true
            anonymous: true
            form_login:
                login_path: /login
                check_path: /login

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
