services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BusinessFinder\EventBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository}'
