<?php

namespace BusinessFinder\DealBundle\Repository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends \Doctrine\ORM\EntityRepository
{
}
