services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BusinessFinder\AppBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

    BusinessFinder\AppBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']